// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2025 Jeremy Hahn
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/transport/grpc/proto/dkg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType identifies DKG protocol messages
type MessageType int32

const (
	MessageType_MSG_TYPE_UNSPECIFIED  MessageType = 0
	MessageType_MSG_TYPE_JOIN         MessageType = 1  // Participant joining session
	MessageType_MSG_TYPE_SESSION_INFO MessageType = 2  // Session info from coordinator
	MessageType_MSG_TYPE_ROUND1       MessageType = 3  // Round 1 broadcast
	MessageType_MSG_TYPE_ROUND1_AGG   MessageType = 4  // Aggregated round 1 from coordinator
	MessageType_MSG_TYPE_ROUND2       MessageType = 5  // Round 2 shares
	MessageType_MSG_TYPE_ROUND2_AGG   MessageType = 6  // Aggregated round 2 from coordinator
	MessageType_MSG_TYPE_CERT_EQ_SIGN MessageType = 7  // CertEq signature
	MessageType_MSG_TYPE_CERTIFICATE  MessageType = 8  // Final certificate
	MessageType_MSG_TYPE_ERROR        MessageType = 9  // Error message
	MessageType_MSG_TYPE_COMPLETE     MessageType = 10 // DKG complete
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MSG_TYPE_UNSPECIFIED",
		1:  "MSG_TYPE_JOIN",
		2:  "MSG_TYPE_SESSION_INFO",
		3:  "MSG_TYPE_ROUND1",
		4:  "MSG_TYPE_ROUND1_AGG",
		5:  "MSG_TYPE_ROUND2",
		6:  "MSG_TYPE_ROUND2_AGG",
		7:  "MSG_TYPE_CERT_EQ_SIGN",
		8:  "MSG_TYPE_CERTIFICATE",
		9:  "MSG_TYPE_ERROR",
		10: "MSG_TYPE_COMPLETE",
	}
	MessageType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED":  0,
		"MSG_TYPE_JOIN":         1,
		"MSG_TYPE_SESSION_INFO": 2,
		"MSG_TYPE_ROUND1":       3,
		"MSG_TYPE_ROUND1_AGG":   4,
		"MSG_TYPE_ROUND2":       5,
		"MSG_TYPE_ROUND2_AGG":   6,
		"MSG_TYPE_CERT_EQ_SIGN": 7,
		"MSG_TYPE_CERTIFICATE":  8,
		"MSG_TYPE_ERROR":        9,
		"MSG_TYPE_COMPLETE":     10,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_transport_grpc_proto_dkg_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_pkg_transport_grpc_proto_dkg_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_proto_dkg_proto_rawDescGZIP(), []int{0}
}

// DKGMessage is the envelope for all DKG protocol messages
type DKGMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`  // Session identifier
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=dkg.MessageType" json:"type,omitempty"`       // Message type
	SenderIdx     int32                  `protobuf:"varint,3,opt,name=sender_idx,json=senderIdx,proto3" json:"sender_idx,omitempty"` // Sender's participant index
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                       // Serialized message payload
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // Unix timestamp (milliseconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DKGMessage) Reset() {
	*x = DKGMessage{}
	mi := &file_pkg_transport_grpc_proto_dkg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DKGMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGMessage) ProtoMessage() {}

func (x *DKGMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_proto_dkg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGMessage.ProtoReflect.Descriptor instead.
func (*DKGMessage) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_proto_dkg_proto_rawDescGZIP(), []int{0}
}

func (x *DKGMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DKGMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_TYPE_UNSPECIFIED
}

func (x *DKGMessage) GetSenderIdx() int32 {
	if x != nil {
		return x.SenderIdx
	}
	return 0
}

func (x *DKGMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DKGMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_transport_grpc_proto_dkg_proto protoreflect.FileDescriptor

const file_pkg_transport_grpc_proto_dkg_proto_rawDesc = "" +
	"\n" +
	"\"pkg/transport/grpc/proto/dkg.proto\x12\x03dkg\"\xa8\x01\n" +
	"\n" +
	"DKGMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.dkg.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"sender_idx\x18\x03 \x01(\x05R\tsenderIdx\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp*\x91\x02\n" +
	"\vMessageType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMSG_TYPE_JOIN\x10\x01\x12\x19\n" +
	"\x15MSG_TYPE_SESSION_INFO\x10\x02\x12\x13\n" +
	"\x0fMSG_TYPE_ROUND1\x10\x03\x12\x17\n" +
	"\x13MSG_TYPE_ROUND1_AGG\x10\x04\x12\x13\n" +
	"\x0fMSG_TYPE_ROUND2\x10\x05\x12\x17\n" +
	"\x13MSG_TYPE_ROUND2_AGG\x10\x06\x12\x19\n" +
	"\x15MSG_TYPE_CERT_EQ_SIGN\x10\a\x12\x18\n" +
	"\x14MSG_TYPE_CERTIFICATE\x10\b\x12\x12\n" +
	"\x0eMSG_TYPE_ERROR\x10\t\x12\x15\n" +
	"\x11MSG_TYPE_COMPLETE\x10\n" +
	"2K\n" +
	"\x0eDKGCoordinator\x129\n" +
	"\x11ParticipantStream\x12\x0f.dkg.DKGMessage\x1a\x0f.dkg.DKGMessage(\x010\x01BBZ@github.com/jeremyhahn/go-frostdkg/pkg/transport/grpc/proto;protob\x06proto3"

var (
	file_pkg_transport_grpc_proto_dkg_proto_rawDescOnce sync.Once
	file_pkg_transport_grpc_proto_dkg_proto_rawDescData []byte
)

func file_pkg_transport_grpc_proto_dkg_proto_rawDescGZIP() []byte {
	file_pkg_transport_grpc_proto_dkg_proto_rawDescOnce.Do(func() {
		file_pkg_transport_grpc_proto_dkg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_transport_grpc_proto_dkg_proto_rawDesc), len(file_pkg_transport_grpc_proto_dkg_proto_rawDesc)))
	})
	return file_pkg_transport_grpc_proto_dkg_proto_rawDescData
}

var file_pkg_transport_grpc_proto_dkg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_transport_grpc_proto_dkg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_transport_grpc_proto_dkg_proto_goTypes = []any{
	(MessageType)(0),   // 0: dkg.MessageType
	(*DKGMessage)(nil), // 1: dkg.DKGMessage
}
var file_pkg_transport_grpc_proto_dkg_proto_depIdxs = []int32{
	0, // 0: dkg.DKGMessage.type:type_name -> dkg.MessageType
	1, // 1: dkg.DKGCoordinator.ParticipantStream:input_type -> dkg.DKGMessage
	1, // 2: dkg.DKGCoordinator.ParticipantStream:output_type -> dkg.DKGMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_transport_grpc_proto_dkg_proto_init() }
func file_pkg_transport_grpc_proto_dkg_proto_init() {
	if File_pkg_transport_grpc_proto_dkg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_transport_grpc_proto_dkg_proto_rawDesc), len(file_pkg_transport_grpc_proto_dkg_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_transport_grpc_proto_dkg_proto_goTypes,
		DependencyIndexes: file_pkg_transport_grpc_proto_dkg_proto_depIdxs,
		EnumInfos:         file_pkg_transport_grpc_proto_dkg_proto_enumTypes,
		MessageInfos:      file_pkg_transport_grpc_proto_dkg_proto_msgTypes,
	}.Build()
	File_pkg_transport_grpc_proto_dkg_proto = out.File
	file_pkg_transport_grpc_proto_dkg_proto_goTypes = nil
	file_pkg_transport_grpc_proto_dkg_proto_depIdxs = nil
}
