// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2025 Jeremy Hahn
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: pkg/transport/grpc/proto/dkg.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DKGCoordinator_ParticipantStream_FullMethodName = "/dkg.DKGCoordinator/ParticipantStream"
)

// DKGCoordinatorClient is the client API for DKGCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DKGCoordinator service provides gRPC transport for FROST-DKG protocol.
// The coordinator acts as a relay server with no cryptographic role.
type DKGCoordinatorClient interface {
	// ParticipantStream establishes a bidirectional stream for DKG message exchange.
	// Participants connect to this stream and exchange messages throughout the DKG protocol.
	ParticipantStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DKGMessage, DKGMessage], error)
}

type dKGCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewDKGCoordinatorClient(cc grpc.ClientConnInterface) DKGCoordinatorClient {
	return &dKGCoordinatorClient{cc}
}

func (c *dKGCoordinatorClient) ParticipantStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DKGMessage, DKGMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DKGCoordinator_ServiceDesc.Streams[0], DKGCoordinator_ParticipantStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DKGMessage, DKGMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DKGCoordinator_ParticipantStreamClient = grpc.BidiStreamingClient[DKGMessage, DKGMessage]

// DKGCoordinatorServer is the server API for DKGCoordinator service.
// All implementations must embed UnimplementedDKGCoordinatorServer
// for forward compatibility.
//
// DKGCoordinator service provides gRPC transport for FROST-DKG protocol.
// The coordinator acts as a relay server with no cryptographic role.
type DKGCoordinatorServer interface {
	// ParticipantStream establishes a bidirectional stream for DKG message exchange.
	// Participants connect to this stream and exchange messages throughout the DKG protocol.
	ParticipantStream(grpc.BidiStreamingServer[DKGMessage, DKGMessage]) error
	mustEmbedUnimplementedDKGCoordinatorServer()
}

// UnimplementedDKGCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDKGCoordinatorServer struct{}

func (UnimplementedDKGCoordinatorServer) ParticipantStream(grpc.BidiStreamingServer[DKGMessage, DKGMessage]) error {
	return status.Error(codes.Unimplemented, "method ParticipantStream not implemented")
}
func (UnimplementedDKGCoordinatorServer) mustEmbedUnimplementedDKGCoordinatorServer() {}
func (UnimplementedDKGCoordinatorServer) testEmbeddedByValue()                        {}

// UnsafeDKGCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DKGCoordinatorServer will
// result in compilation errors.
type UnsafeDKGCoordinatorServer interface {
	mustEmbedUnimplementedDKGCoordinatorServer()
}

func RegisterDKGCoordinatorServer(s grpc.ServiceRegistrar, srv DKGCoordinatorServer) {
	// If the following call panics, it indicates UnimplementedDKGCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DKGCoordinator_ServiceDesc, srv)
}

func _DKGCoordinator_ParticipantStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DKGCoordinatorServer).ParticipantStream(&grpc.GenericServerStream[DKGMessage, DKGMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DKGCoordinator_ParticipantStreamServer = grpc.BidiStreamingServer[DKGMessage, DKGMessage]

// DKGCoordinator_ServiceDesc is the grpc.ServiceDesc for DKGCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DKGCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dkg.DKGCoordinator",
	HandlerType: (*DKGCoordinatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ParticipantStream",
			Handler:       _DKGCoordinator_ParticipantStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/transport/grpc/proto/dkg.proto",
}
